server:
  port: 8083

spring:
  application:
    name: delivery
  datasource:
    url: jdbc:postgresql://ep-misty-credit-a59y8o5v-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_PvN8fn4lMrZC
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

order:
  service:
    url: http://localhost:8000
user:
  service:
    url: http://localhost:8081

    # Eureka Client
    eureka:
      client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
          defaultZone: http://localhost:8761/eureka
      instance:
        prefer-ip-address: true

