apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliveries
  labels:
    app: deliveries
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliveries
  template:
    metadata:
      labels:
        app: deliveries
    spec:
      containers:
        - name: microservice-deliveries
          image: juanjoher/imagenes:microservice-deliveries
          ports:
            - containerPort: 8083
          env:
            - name: SERVER_PORT
              value: "8083"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"