apiVersion: v1
kind: Service
metadata:
  name: microservice-deliveries
spec:
  selector:
    app: microservice-deliveries
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8083
  type: ClusterIP